name: Code Quality

on: [pull_request]

jobs:
  Flake8:
    runs-on: ubuntu-latest
    name: flake8-Runner
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: flake8
  Black:
    name: Black-Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-black@v2
        with:
          github_token: ${{ secrets.github_token }}
          tool_name: Black 
          filter_mode: nofilter
  PyTest:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Install Poetry Dependecies
        run: poetry install
      - name: Run PyTest
        run: poetry run pytest
